### ISSUE TITLE
set_data_source method is not exists

### ISSUE THREAD

**Issue by jospic** [TheBrunoCA/BetterTable#1]
Hi,
trying the example code shown in the descripion page reveals that the method set_data_source() is not present in the main plugin functions.

Is it possible to have a working example demo?

Thanks in advance.
-j

**Comment by TheBrunoCA** [comment]
Hi jospic,
It was my fault, I refactored some code and forgot to create a new branch, I'm still learning to use GitHub correctly.
 I will update the documentation as soon as possible, thanks for the feedback.
